name: "🕒 PERT Duration Estimates"
description: "Capture optimistic, most‑likely and pessimistic hour estimates for sprint forecasting."
title: "[Task]: "
labels: ['task', 'sprint-forecast']
assignees: ['emmett08']
body:
  - type: markdown
    attributes:
      value: |
        ## Purpose
        This ticket collects **PERT duration estimates** for a single work item.
        Please fill in the three time estimates below; they will feed the sprint‑forecast engine.

        - **Optimistic (o)** – best‑case, no bumps.
        - **Most likely (m)** – normal outcome.
        - **Pessimistic (p)** – worst‑case with delays.

        *Enter all durations in **hours**; use decimals for fractions (e.g. `0.5`).*

  - type: input
    id: o
    attributes:
      label: "Optimistic (o)"
      description: "Optimistic duration in hours."
      placeholder: "1"
    validations:
      required: true

  - type: input
    id: m
    attributes:
      label: "Most likely (m)"
      description: "Most likely duration in hours."
      placeholder: "3"
    validations:
      required: true

  - type: input
    id: p
    attributes:
      label: "Pessimistic (p)"
      description: "Pessimistic duration in hours."
      placeholder: "5"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Scheduling and Dependencies
        Optionally note the sprint milestone and any blockers.

  - type: input
    id: sprint-milestone
    attributes:
      label: "Sprint milestone"
      description: "Sprint or milestone name/number (optional). You can also set it later in the sidebar."
      placeholder: "Sprint 6"
    validations:
      required: false

  - type: input
    id: blocked-by
    attributes:
      label: "Blocked by"
      description: "Blocking issues or tasks (optional, comma‑separated)."
      placeholder: "#42, #99"
    validations:
      required: false

  - type: textarea
    id: task-description
    attributes:
      label: "Task Description"
      description: "Free‑form details about the task."
      placeholder: "Add any additional context…"
    validations:
      required: false
