name: ci

on: [push, pull_request]

jobs:
  pypi-install-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - run: python -m pip install --upgrade pip
      - run: pip install sprintforecast==0.1.0
      - run: sprintforecast --help
